Revert "Frontend update ci"

diff --git a/.github/workflows/frontend-ci.yml b/.github/workflows/frontend-ci.yml
--- a/.github/workflows/frontend-ci.yml
+++ b/.github/workflows/frontend-ci.yml
@@ -26,16 +26,26 @@ jobs:
         run: |
           npm install
 
-      - name: Run TS Tests
+      # note: we will turn this back on once all files are made
+      # - name: Run TS Linter
+      #   run: |
+      #     echo "Running linter locally on all ts files in ./frontend/"
 
+      #     npx eslint .
+
+      #     LINTER_EXIT_CODE=$?
+      #     if [ $LINTER_EXIT_CODE -ne 0 ]; then
+      #       echo "TS Linter found errors, failing the job."
+      #       exit $LINTER_EXIT_CODE
+      #     else
+      #       echo "TS Linter passed, no errors found."
+      #     fi
+
+      - name: Run TS Tests
         run: |
           echo "Running Test locally on all *.test.ts files in ./unit_test/"
 
-          cd frontend
-
-          cd unit_test
-
-          npx mocha -r ts-node/register setup.ts general/**.test.ts
+          npx mocha -r ts-node/register "**/*.test.ts"
 
           TESTING_EXIT_CODE=$?
           if [ $TESTING_EXIT_CODE -ne 0 ]; then
